#!/usr/bin/with-contenv bash

_term() {
	echo "Caught SIGTERM for autodl!"
	killall -s SIGTERM irssi 2>/dev/null
	sleep 1
}

trap _term SIGTERM

HOME=/config dtach -N /detach_sess/.autodl \
	s6-setuidgid abc /usr/bin/irssi --home=/config/.irssi &

wait

sleep 1s
