#!/usr/bin/with-contenv bash

if [ -f "/detach_sess/.irssi" ]; then
	rm -f /detach_sess/.irssi || true
	sleep 1s
fi

HOME=/config; dtach -N /detach_sess/.irssi s6-setuidgid abc /usr/bin/irssi --home=/config/.irssi

sleep 1s
