#!/usr/bin/with-contenv bash

_term() {
	echo "Caught SIGTERM for rtorrent!"
	killall -s SIGTERM rtorrent 2>/dev/null
}

trap _term SIGTERM

RTORRENT_LOCK="/detach_sess/.rtorrent"
echo "# Checking rtorrent session lock ${RTORRENT_LOCK}"
# Check if session lock wasn't deleted
if [ -S "${RTORRENT_LOCK}" ] && ! pgrep rtorrent > /dev/null; then
	echo "# rtorrent process not found, removing session lock ${RTORRENT_LOCK}"
	rm -f "${RTORRENT_LOCK}"
fi

exec s6-setuidgid abc dtach -N "${RTORRENT_LOCK}" \
	/usr/bin/rtorrent \
		-n -o import=/config/rtorrent/rtorrent.rc &

DTACH_PID=$!
echo "# rtorrent dtach session started ${DTACH_PID}"
wait ${DTACH_PID}
echo "# rtorrent dtach session finished ${DTACH_PID}"

sleep 1
