#!/usr/bin/with-contenv bash

_term() {
	echo "Caught SIGTERM for rtorrent!"
	killall -s SIGINT rtorrent 2>/dev/null
	sleep 1
}

	trap _term SIGTERM

	screen -D -m -S rtorrent \
		s6-setuidgid abc /usr/bin/rtorrent \
			-n -o import=/config/rtorrent/rtorrent.rc &

wait
