#!/usr/bin/with-contenv bash

cat << EOF
-------------------------------------
                 __             .___.__
  _____   __ ___/  |_  ____   __| _/|  |
  \__  \ |  |  \   __\/  _ \ / __ | |  |
   / __ \|  |  /|  | (  <_> ) /_/ | |  |__
  (____  /____/ |__|  \____/\____ | |____/
       \/                        \/

 Author  : horjulf
 URL     : https://github.com/horjulf/docker-rutorrent-autodl
 Based on: https://github.com/linuxserver/docker-rutorrent

 Part of the Cloudbox project: https://cloudbox.rocks

-------------------------------------
EOF
