#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config/tmp

# copy config files/set links etc...
[[ ! -L /home/abc/.autodl ]] && ln -s /config/.autodl /home/abc/.autodl
[[ ! -L /config/.irssi/scripts/autorun/autodl-irssi.pl ]] && ln -s /config/.irssi/scripts/autodl-irssi.pl /config/.irssi/scripts/autorun/autodl-irssi.pl
[[ ! -L /config/.irssi/scripts/AutodlIrssi/trackers ]] && (
	rm -rf /config/.irssi/scripts/AutodlIrssi/trackers && \
	ln -s /config/.irssi/trackers/trackers /config/.irssi/scripts/AutodlIrssi/trackers
)
[[ ! -f /config/.autodl/autodl.cfg ]] && cp /defaults/autodl/autodl.cfg /config/.autodl/autodl.cfg
[[ ! -f /usr/share/webapps/rutorrent/plugins/autodl-irssi/conf.php ]] && cp /defaults/autodl/conf.php /usr/share/webapps/rutorrent/plugins/autodl-irssi/conf.php

# Symlink previous manual `curl` install
[[ ! -L /usr/local/bin/curl ]] && ln -s /usr/bin/curl /usr/local/bin/curl

# set perms
chown -R abc:abc \
	/config \
	/usr/share/webapps/rutorrent
